// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'tour_shopping.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$TourShoppingImpl _$$TourShoppingImplFromJson(Map<String, dynamic> json) =>
    _$TourShoppingImpl(
      contentId: json['contentId'] as String,
      contentTypeId: json['contentTypeId'] as String,
      title: json['title'] as String,
      address1: json['address1'] as String?,
      address2: json['address2'] as String?,
      areaCode: json['areaCode'] as String?,
      sigunguCode: json['sigunguCode'] as String?,
      cat1: json['cat1'] as String?,
      cat2: json['cat2'] as String?,
      cat3: json['cat3'] as String?,
      firstImage: json['firstImage'] as String?,
      firstImage2: json['firstImage2'] as String?,
      mapX: (json['mapX'] as num?)?.toDouble(),
      mapY: (json['mapY'] as num?)?.toDouble(),
      tel: json['tel'] as String?,
      zipCode: json['zipCode'] as String?,
      openTime: json['openTime'] as String?,
      openDate: json['openDate'] as String?,
      restDate: json['restDate'] as String?,
      saleItem: json['saleItem'] as String?,
      saleItemCost: json['saleItemCost'] as String?,
      fairDay: json['fairDay'] as String?,
      shopGuide: json['shopGuide'] as String?,
      parking: json['parking'] as String?,
      restroom: json['restroom'] as String?,
      infoCenter: json['infoCenter'] as String?,
      scale: json['scale'] as String?,
      babyCarriage: json['babyCarriage'] as String?,
      petPossible: json['petPossible'] as String?,
      creditCard: json['creditCard'] as String?,
      culturalCenter: json['culturalCenter'] as String?,
      distance: (json['distance'] as num?)?.toDouble(),
      isBookmarked: json['isBookmarked'] as bool? ?? false,
      createdTime: json['createdTime'] as String?,
      modifiedTime: json['modifiedTime'] as String?,
    );

Map<String, dynamic> _$$TourShoppingImplToJson(_$TourShoppingImpl instance) =>
    <String, dynamic>{
      'contentId': instance.contentId,
      'contentTypeId': instance.contentTypeId,
      'title': instance.title,
      'address1': instance.address1,
      'address2': instance.address2,
      'areaCode': instance.areaCode,
      'sigunguCode': instance.sigunguCode,
      'cat1': instance.cat1,
      'cat2': instance.cat2,
      'cat3': instance.cat3,
      'firstImage': instance.firstImage,
      'firstImage2': instance.firstImage2,
      'mapX': instance.mapX,
      'mapY': instance.mapY,
      'tel': instance.tel,
      'zipCode': instance.zipCode,
      'openTime': instance.openTime,
      'openDate': instance.openDate,
      'restDate': instance.restDate,
      'saleItem': instance.saleItem,
      'saleItemCost': instance.saleItemCost,
      'fairDay': instance.fairDay,
      'shopGuide': instance.shopGuide,
      'parking': instance.parking,
      'restroom': instance.restroom,
      'infoCenter': instance.infoCenter,
      'scale': instance.scale,
      'babyCarriage': instance.babyCarriage,
      'petPossible': instance.petPossible,
      'creditCard': instance.creditCard,
      'culturalCenter': instance.culturalCenter,
      'distance': instance.distance,
      'isBookmarked': instance.isBookmarked,
      'createdTime': instance.createdTime,
      'modifiedTime': instance.modifiedTime,
    };
