// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'tour_stay.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$TourStayImpl _$$TourStayImplFromJson(Map<String, dynamic> json) =>
    _$TourStayImpl(
      contentId: json['contentId'] as String,
      title: json['title'] as String,
      address1: json['address1'] as String?,
      address2: json['address2'] as String?,
      areaCode: json['areaCode'] as String?,
      sigunguCode: json['sigunguCode'] as String?,
      mapX: (json['mapX'] as num?)?.toDouble(),
      mapY: (json['mapY'] as num?)?.toDouble(),
      firstImage: json['firstImage'] as String?,
      firstImage2: json['firstImage2'] as String?,
      tel: json['tel'] as String?,
      zipCode: json['zipCode'] as String?,
      homepage: json['homepage'] as String?,
      overview: json['overview'] as String?,
      checkInTime: json['checkInTime'] as String?,
      checkOutTime: json['checkOutTime'] as String?,
      roomType: json['roomType'] as String?,
      roomCount: (json['roomCount'] as num?)?.toInt(),
      parking: json['parking'] as String?,
      reservationUrl: json['reservationUrl'] as String?,
      reservationTel: json['reservationTel'] as String?,
      accomCount: json['accomCount'] as String?,
      foodPlace: json['foodPlace'] as String?,
      pickup: json['pickup'] as String?,
      cooking: json['cooking'] as String?,
      barbecue: json['barbecue'] as String?,
      fitness: json['fitness'] as String?,
      sauna: json['sauna'] as String?,
      publicBath: json['publicBath'] as String?,
      publicPc: json['publicPc'] as String?,
      seminar: json['seminar'] as String?,
      sports: json['sports'] as String?,
      refundPolicy: json['refundPolicy'] as String?,
      hanOk: json['hanOk'] as bool?,
      goodStay: json['goodStay'] as bool?,
      cat1: json['cat1'] as String?,
      cat2: json['cat2'] as String?,
      cat3: json['cat3'] as String?,
      createdTime: json['createdTime'] as String?,
      modifiedTime: json['modifiedTime'] as String?,
      cpyrhtDivCd: json['cpyrhtDivCd'] as String?,
      mlevel: (json['mlevel'] as num?)?.toInt(),
      distance: (json['distance'] as num?)?.toDouble(),
      isBookmarked: json['isBookmarked'] as bool? ?? false,
      cachedAt: json['cachedAt'] == null
          ? null
          : DateTime.parse(json['cachedAt'] as String),
    );

Map<String, dynamic> _$$TourStayImplToJson(_$TourStayImpl instance) =>
    <String, dynamic>{
      'contentId': instance.contentId,
      'title': instance.title,
      'address1': instance.address1,
      'address2': instance.address2,
      'areaCode': instance.areaCode,
      'sigunguCode': instance.sigunguCode,
      'mapX': instance.mapX,
      'mapY': instance.mapY,
      'firstImage': instance.firstImage,
      'firstImage2': instance.firstImage2,
      'tel': instance.tel,
      'zipCode': instance.zipCode,
      'homepage': instance.homepage,
      'overview': instance.overview,
      'checkInTime': instance.checkInTime,
      'checkOutTime': instance.checkOutTime,
      'roomType': instance.roomType,
      'roomCount': instance.roomCount,
      'parking': instance.parking,
      'reservationUrl': instance.reservationUrl,
      'reservationTel': instance.reservationTel,
      'accomCount': instance.accomCount,
      'foodPlace': instance.foodPlace,
      'pickup': instance.pickup,
      'cooking': instance.cooking,
      'barbecue': instance.barbecue,
      'fitness': instance.fitness,
      'sauna': instance.sauna,
      'publicBath': instance.publicBath,
      'publicPc': instance.publicPc,
      'seminar': instance.seminar,
      'sports': instance.sports,
      'refundPolicy': instance.refundPolicy,
      'hanOk': instance.hanOk,
      'goodStay': instance.goodStay,
      'cat1': instance.cat1,
      'cat2': instance.cat2,
      'cat3': instance.cat3,
      'createdTime': instance.createdTime,
      'modifiedTime': instance.modifiedTime,
      'cpyrhtDivCd': instance.cpyrhtDivCd,
      'mlevel': instance.mlevel,
      'distance': instance.distance,
      'isBookmarked': instance.isBookmarked,
      'cachedAt': instance.cachedAt?.toIso8601String(),
    };
